spring:
  config:
    import: optional:classpath:secret-application.yml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false

jwt:
  secret: my-super-secret-key-1234567890123456
  expiration: 3600000




server:
  port: 8080