spring:
  config:
    import: optional:classpath:secret-application.yml
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false




server:
  port: 8080