spring:
  config:
    import: optional:classpath:secret-application.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  datasource:
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 3000
      connection-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 1800000
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000




server:
  port: 8080